### ISSUE TITLE
Documenti troppo stretti.

### ISSUE THREAD

**Issue by jstringara** [AIM-mate/AIM-watermark#2]
Come rilevato da Francesco durante la riunione del 18-09-2024, se il documento a cui si vuole applicare la filigrana ha un formato più stretto dell'A4 questo non funziona.

In parole povere: i due documenti vengono effettivamente uniti ma la porzione visibile esclude il watermark.

**Comment by Dr4k3z** [comment]
Ci guardo, ma ho una domanda: come ce ne siamo accorti? Abbiamo provato ad aggiungere il watermark ad una roba che non era A4? Qualcosa dal portale appunti immagino. 

La soluzione _brute force_ ti riformattare il pdf in A4  è praticabile?

**Comment by jstringara** [comment]
Sì, Francesco ha provato a watermarkare un pdf ma non è venuto fuori niente.
Il file si chiama "Fisica sperimentale 1" ed è il classico quaderno di GoodNotes stampato (che ha sempre causato un botto di problemi).

Anche io di base proverei a riformattare tutto in formato A4 (anche solo per uniformità) ma [non so quanto questa idea sia effettivamente praticabile](https://stackoverflow.com/questions/75257369/pypdf2-paper-size-manipulation). 

In ogni caso, se riusciamo credo che sia io che @teobucci ci daremo un occhiata.

@Dr4k3z crea il tuo branche che poi apriamo una bella PR (@teobucci docet)

**Comment by Dr4k3z** [comment]
Fork e PR creata. 
Ho aggiunto una funzione che controlla che il file in questione sia effettivamente A4. Al momento crea semplicemnte un warning; implementero' anche il resize. 

commit #3 cb840db2ebfa6cb8eab6a2526910c93b473b6c75
